### ISSUE TITLE
[Weather:data] Dto & Model 작성

### ISSUE THREAD

**Issue by Gunbam27** [Gunbam27/weather_project#3]
## 목적
weather Dto & 모델 클래스 작성

## 상세 사항
-온도
-지역(경도 위도)
-웨더코드
-dto 무지성
-모델(time/temperature_2m/rain/weather_code)

**Comment by jungeun272** [comment]
백두산
경도: 약 128.05도
위도: 약 42.00도
금강산
경도: 약 127.73도
위도: 약 38.70도
설악산
경도: 약 128.53도
위도: 약 38.07도
지리산
경도: 약 127.63도
위도: 약 35.79도
한라산
경도: 약 126.53도
위도: 약 33.36도
북한산
경도: 약 126.96도
위도: 약 37.66도

**Comment by frihett** [comment]
좋아요
